# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8dd761604cb11fe85aeca17a8682ddb4e4b0cecb2c6b9b6d1e290d241a38337ba46930db22302205a987c16db03347e9974d100e7ac978dda826a8ea69a1633

test:
  secret_key_base: 0ab52888c6c3e42b45edc82e7d70d36f63786906a3d786ae989d81b259ede7ea7efd420a5dadd3f4949b2f6c559e3dde36d99f247bbd8e2f337c1600798f7a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
